Exercises/Controllers/GameController.cs
using Exercises.Account;
using Exercises.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercises.Controllers
{
    public class GameController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCode(Guid uid)
        {
            JsonResult ret = new JsonResult();
            ret.Data = db.Code_t.Where(p => p.Code_ApplicationUid == uid).ToList();
            return ret;
        }
        public JsonResult PostCode(Guid uid, string code, string name)
        {
            JsonResult ret = new JsonResult();
            try
            {
                Code_t c = new Code_t();
                c.Code_Content = code;
                c.Code_Name = name;
                c.Code_UpdateTime = DateTime.Now;
                c.Code_CreateTime = c.Code_UpdateTime;
                c.Code_Author = CookieManage.GetUserinfo();
                c.Code_ApplicationUid = uid;

                db.Code_t.Add(c);
                db.SaveChanges();
                ret.Data = true;
            }
            catch
            {
                ret.Data = false;
            }
            return ret;
        }
    }
}

Exercises/Controllers/SQLController.cs
using Newtonsoft.Json;
using SQLUtils;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercises.Controllers
{
    public class SQLController : Controller
    {
        // GET: SQL
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult UpLoad(HttpPostedFileBase file)
        {
            JsonResult ret = new JsonResult();
            var fileName = Path.Combine(Request.MapPath("~/Upload"), Path.GetFileName(file.FileName));
            ret.Data = JsonConvert.SerializeObject(CSV(file.InputStream));

            return ret;
        }
        public JsonResult ToSql(HttpPostedFileBase file)
        {
            JsonResult ret = new JsonResult();
            var fileName = Path.Combine(Request.MapPath("~/Upload"), Path.GetFileName(file.FileName));

            ret.Data = TableToSQL.ToSql(CSV(file.InputStream));
            return ret;
        }
        public FileResult DownExample()
        {
            MemoryStream output = new System.IO.MemoryStream();
            StreamWriter writer = new System.IO.StreamWriter(output, System.Text.Encoding.UTF8);
            string s = $"{TableToSQL.KEY_Tables},{TableToSQL.KEY_Columns},{TableToSQL.KEY_Types},{TableToSQL.KEY_Key},{TableToSQL.KEY_Identity},{TableToSQL.KEY_IsNull},{TableToSQL.KEY_Default}";
            writer.Write(s);//输出标题，逗号分割（注意最后一列不加逗号）
            writer.WriteLine();

            writer.Flush();
            output.Position = 0;
            return File(output, "text/comma-separated-values", "实例文档.csv");
        }
        public DataTable CSV(Stream str)
        {

            //try
            //{
            String line;
            String[] split = null;
            DataTable table = new DataTable();
            DataRow row = null;
            StreamReader sr = new StreamReader(str, System.Text.Encoding.Default);
            //创建与数据源对应的数据列 
            line = sr.ReadLine();
            split = line.Split(',');
            foreach (String colname in split)
            {
                table.Columns.Add(colname, System.Type.GetType("System.String"));
            }
            //将数据填入数据表 
            int j = 0;
            while ((line = sr.ReadLine()) != null)
            {
                j = 0;
                row = table.NewRow();
                split = line.Split(',');

                //解决csv单元格中有逗号的情况
                List<string> columns = new List<string>();
                bool longword = false;
                string temp = "";
                foreach (var item in split)
                {

                    if (item != "" && item[0] == '\"')
                    {
                        longword = true;

                    }

                    if (longword)
                    {
                        temp += "," + item;
                        if (item != "" && item[item.Length - 1] == '\"')
                        {
                            longword = false;

                            columns.Add(temp.Trim(new char[] { ',', '"', ' ' }));
                            temp = "";
                        }
                    }
                    else
                    {
                        columns.Add(item);
                    }

                }


                foreach (String colname in columns)
                {
                    if (colname != null)
                        row[j] = colname;
                    j++;
                }
                table.Rows.Add(row);
            }
            sr.Close();
            //显示数据 
            return table;
 
            GC.Collect();

        }
  //      public ActionResult Test()
  //      {
  //          string con = "Server=192.168.1.70;Database=dpnetwork_data;uid=sa;pwd=bmc!1234+";
  //          string sqlcommend = @"SELECT TOP 1000 [Fld_Id]
  //    ,[Fld_MaxValue]
  //    ,[Fld_MinValue]
  //    ,[Fld_Time]
  //    ,[Fld_TotalValue]
  //    ,[Fld_OriTotalValue]
  //    ,[Fld_AFUid]
  //    ,[Fld_FlowMeterUid]
  //FROM [dpnetwork_data].[dbo].[FlowDay_t]";
  //          DataTable dt = Reader(con, sqlcommend);


  //          return View();
  //      }
        public JsonResult SQL(string sql, string con)
        {

            JsonResult js = new JsonResult();
            js.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if (sql.ToLower().Contains("select"))
            {
                js.Data = JsonConvert.SerializeObject(Reader(con, sql));
            }
            else
            {
                js.Data = Writer(con, sql);
            }

            return js;
        }
        Func<string, string, DataTable> Reader = (cs, sql) =>
        {
            SqlConnection con = new SqlConnection(cs);
            con.Open();

            SqlCommand cmd = new SqlCommand();
            cmd.CommandText = sql;
            cmd.Connection = con;
            SqlDataAdapter dbAdapter = new SqlDataAdapter(cmd);
            DataTable ds = new DataTable();
            dbAdapter.Fill(ds);
            con.Close();
            return ds;
        };
        Func<string, string, int> Writer = (cs, sql) =>
        {
            SqlConnection con = new SqlConnection(cs);
            con.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.CommandText = sql;
            cmd.Connection = con;
            int num = cmd.ExecuteNonQuery();
            con.Close();
            return num;
        };
    }
}

Exercises/Views/Shared/_Layout.cshtml
@using Exercises.Account
@{
    var IsLogin = CookieManage.HasUserinfo();
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>legen的小工具</title>
    <link rel="icon" href="~/Content/font-awesome.css" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/心跳.png">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <style>
        #particles-js {
            width: 100%;
            height: 100%;
            background-color: #ffffff;
            background-image: url('');
            background-size: cover;
            background-position: 50% 50%;
            background-repeat: no-repeat;
        }
    </style>
    @*<script>
        $(document).ready(function () {
            $("#search").validate({
                rules: {
                    words: {required:true}
                },
                messages: {
                    words: {required:"请输入单词"}
                },
                errorPlacement: function (error, element) {
                    $("#search").addClass("has-error");
                    $(element).attr('placeholder', error[0].innerText)
            },

            });
        });
    </script>*@
</head>
<body>
    <div id="particles-js" style="z-index:-1;position:absolute"></div>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Legen的小工具", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("关于", "About", "Home")</li>*@
                    <li>@Html.ActionLink("云数据库管理", "index", "SQL")</li>
                    <li>@Html.ActionLink("游戏", "index", "Game")</li>
                    @*<li>@Html.ActionLink("算法", "index", "Algorithm")</li>*@
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                @*<form class="navbar-form navbar-left" id="search" role="search" method="get" action="/home/search">
                    <div class="form-group">
                        <input type="text" class="form-control " name="words" id="words" placeholder="输入六级单词">
                    </div>

                    <button type="submit" class="btn btn-default">搜索</button>
                </form>*@
                <ul class="nav navbar-nav navbar-right">
                    @if (!IsLogin)
                    {
                        <li><a href="/user/login">去登录</a></li>
                    }
                    else
                    {
                        <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@CookieManage.GetUserinfo() <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#" id="message">个人信息</a></li>
                                <li><a href="#">计划管理</a></li>
                                <li><a href="#">学习记录</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/user/logout">退出登录</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - legen的小工具</p>
        </footer>
    </div>
    <script src="~/Scripts/particles.js"></script>
    <script src="~/Scripts/app.js"></script>
</body>

</html>